services:
  selenium-hub:
    image: selenium/hub
    container_name: seleniumHub
    ports:
      - "4442-4444:4442-4444"
    networks:
      - seleniumgrid

  chrome:
    image: selenium/node-chrome
    container_name: ChromeNode
    shm_size: 2g
    environment:
      - SE_EVENT_BUS_HOST=selenium-hub
      - SE_EVENT_BUS_PUBLISH_PORT=4442
      - SE_EVENT_BUS_SUBSCRIBE_PORT=4443
      - SE_NODE_MAX_SESSIONS=5
      - SCREEN_WIDTH=1920
      - SCREEN_HEIGHT=1080
      - SCREEN_DEPTH=24
    networks:
      - seleniumgrid

  edge:
    image: selenium/node-edge
    container_name: EdgeNode
    shm_size: 2g
    environment:
      - SE_EVENT_BUS_HOST=selenium-hub
      - SE_EVENT_BUS_PUBLISH_PORT=4442
      - SE_EVENT_BUS_SUBSCRIBE_PORT=4443
      - SE_NODE_MAX_SESSIONS=5
    networks:
      - seleniumgrid

  firefox:
    image: selenium/node-firefox
    container_name: FirefoxNode
    shm_size: 2g
    environment:
      - SE_EVENT_BUS_HOST=selenium-hub
      - SE_EVENT_BUS_PUBLISH_PORT=4442
      - SE_EVENT_BUS_SUBSCRIBE_PORT=4443
      - SE_NODE_MAX_SESSIONS=5
    networks:
      - seleniumgrid

  chrome_video:
    image: selenium/video:latest
    volumes:
      - ./videos:/videos
    depends_on:
      - chrome
    environment:
      - DISPLAY_CONTAINER_NAME=chrome
      - FILE_NAME=chrome_video.mp4
    networks:
      - seleniumgrid

  edge_video:
    image: selenium/video:latest
    volumes:
      - ./videos:/videos
    depends_on:
      - edge
    environment:
      - DISPLAY_CONTAINER_NAME=edge
      - FILE_NAME=edge_video.mp4
    networks:
      - seleniumgrid

  firefox_video:
    image: selenium/video:latest
    volumes:
      - ./videos:/videos
    depends_on:
      - firefox
    environment:
      - DISPLAY_CONTAINER_NAME=firefox
      - FILE_NAME=firefox_video.mp4
    networks:
      - seleniumgrid

  jenkins:
    image: jenkins/jenkins:lts
    container_name: Jenkins
    ports:
      - "8080:8080"
      - "50000:50000"
    volumes:
      - jenkins_home:/var/jenkins_home
    networks:
      - seleniumgrid

networks:
  seleniumgrid:
    driver: bridge

volumes:
  jenkins_home:


#services:
#  selenium-hub:
#    image: selenium/hub
#    container_name: seleniumHub
#    ports:
#      - "4442-4444:4442-4444"
#    networks:
#      - seleniumgrid
#
#  chrome:
#    image: selenium/node-chrome
#    container_name: ChromeNode
#    shm_size: 2g
#    environment:
#      - SE_EVENT_BUS_HOST=selenium-hub
#      - SE_EVENT_BUS_PUBLISH_PORT=4442
#      - SE_EVENT_BUS_SUBSCRIBE_PORT=4443
#      - SE_NODE_MAX_SESSIONS=5
#      - SCREEN_WIDTH=1920
#      - SCREEN_HEIGHT=1080
#      - SCREEN_DEPTH=24
#    networks:
#      - seleniumgrid
#
#  edge:
#    image: selenium/node-edge
#    container_name: EdgeNode
#    shm_size: 2g
#    environment:
#      - SE_EVENT_BUS_HOST=selenium-hub
#      - SE_EVENT_BUS_PUBLISH_PORT=4442
#      - SE_EVENT_BUS_SUBSCRIBE_PORT=4443
#      - SE_NODE_MAX_SESSIONS=5
#    networks:
#      - seleniumgrid
#
#  firefox:
#    image: selenium/node-firefox
#    container_name: FirefoxNode
#    shm_size: 2g
#    environment:
#      - SE_EVENT_BUS_HOST=selenium-hub
#      - SE_EVENT_BUS_PUBLISH_PORT=4442
#      - SE_EVENT_BUS_SUBSCRIBE_PORT=4443
#      - SE_NODE_MAX_SESSIONS=5
#    networks:
#      - seleniumgrid
#
#  chrome_video:
#    image: selenium/video:latest
#    volumes:
#      - ./videos:/videos
#    depends_on:
#      - chrome
#    environment:
#      - DISPLAY_CONTAINER_NAME=chrome
#      - FILE_NAME=chrome_video.mp4
#    networks:
#      - seleniumgrid
#
#  edge_video:
#    image: selenium/video:latest
#    volumes:
#      - ./videos:/videos
#    depends_on:
#      - edge
#    environment:
#      - DISPLAY_CONTAINER_NAME=edge
#      - FILE_NAME=edge_video.mp4
#    networks:
#      - seleniumgrid
#
#  firefox_video:
#    image: selenium/video:latest
#    volumes:
#      - ./videos:/videos
#    depends_on:
#      - firefox
#    environment:
#      - DISPLAY_CONTAINER_NAME=firefox
#      - FILE_NAME=firefox_video.mp4
#    networks:
#      - seleniumgrid
#
#networks:
#  seleniumgrid:
#    driver: bridge

